[project]
name = "riktigpatrick"
version = "0.1.0"
description = "Balancing robot with RL control"
requires-python = ">=3.10"
dependencies = [
    "gymnasium",
    "mujoco",
    "dm-control",
    "torch",
    "numpy",
    "mlflow",
    "pandas",
    "pyyaml",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
