defaults:
  - _self_

seed: 42

logging:
  mlflow:
    experiment_name: "rp_training"
    enabled: false
    push_freq: 10

  plot_freq: 100  # Generate plots every N iterations
  save_freq: 1000

rl:
  discount: 0.99
  entropy_scale: 0.01
  value_loss_scale: 1.0
  normalize_returns: true
  use_baseline: true
  init2zeros: false
  load_net: false
  trim_end_steps: 0

reward:
  # These keys need to exactly match the values in patrick/Observables
  reward/step: 1.0
  reward/rp_pitch: -0.1
  reward/fell: 0.0
  reward/wheel_vel: -0.2
  reward/head_pitch: -0.5
  reward/total: 1.0

train:
  policy_lr: 0.0005
  value_lr: 0.03
  grad_clip: 10.0

env:
  step_time: 0.01  # seconds
  randomize: true
  n_parallel: 16

  # Currently masses are normal(MASS, scale * MASS)...
  random_scale: 0.05

  # All units are SI (International System of Units)
  max_wheel_vel: 10.0  # rad/s - maximum wheel velocity
  max_wheel_acc: 500.0  # rad/s² - maximum wheel acceleration

policy:
  restore_id: m-8fa2c04295cb49cfb55dbff83a9116af  # Set to a valid ID to restore a previous policy
  actions:
    act/accelerate_both_wheels:
      type: discrete
      bins: [-300, -200, -150, -100, -75, -50, -25, -10, -5, -2, 0, 2, 5, 10, 25, 50, 75, 100, 150, 200, 300]  # rad/s² - acceleration values for both wheels

    act/head_pitch_vel:
      type: discrete
      bins: [-0.2, -0.1, 0, 0.1, 0.2]  # rad/s - head pitch velocity

  inputs:
    - filter/rp_pitch
    - sens/left_wheel_vel
    - sens/right_wheel_vel
    - sens/head_pitch
    - sens/head_turn
    - env/obs_time
    - sens/gyro
    - sens/acc


